---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-name
spec:
  rules:
  - http:
      paths:
      - path: /app
        backend:
          serviceName: application-service-name
          servicePort: 8080